# This is a basic workflow to help you get started with Actions

name: Chewy2.0Builds

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: docker login
        env: 
          DOCKER_USER: ${{ secrets.DOCKER_USER }} 
          DOCKER_PW:  ${{ secrets.DOCKER_PW }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PW
      # Runs a single command using the runners shell
      - name: docker build chris-chewy-reviews
        run: docker build -f Dockerfile.build -t feckwame/chris-chewy-reviews:gitworkflow_app .

      # Runs a set of commands using the runners shell
      - name: docker build mongo_seeding
        run: docker build -f Dockerfile.seed -t feckwame/chris-chewy-reviews:gitworkflow_db_seeding .
      - name: docker push
        run: |
          docker push feckwame/chris-chewy-reviews:gitworkflow_app
          docker push feckwame/chris-chewy-reviews:gitworkflow_db_seeding
