name: Chewy2.0Builds
on:
  push:
    branches: [ master ]
  merge:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PW:  ${{ secrets.DOCKER_PW }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PW
      - name: docker build chris-chewy-reviews
        run: docker build -f Dockerfile.build -t feckwame/chris-chewy-reviews:app .
      - name: docker build mongo_seeding
        run: docker build -f Dockerfile.seed -t feckwame/chris-chewy-reviews:db_seeding .
      - name: docker push
        run: |
          docker push feckwame/chris-chewy-reviews:app
          docker push feckwame/chris-chewy-reviews:db_seeding
